CREATE TABLE IF NOT EXISTS servers (
	id VARCHAR(100) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	private BOOLEAN DEFAULT TRUE,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
	hash TEXT NOT NULL UNIQUE,
	server VARCHAR(100) NOT NULL REFERENCES servers (id) ON DELETE CASCADE,
	date BIGINT NOT NULL,
	guilds JSONB NOT NULL,
	players JSONB NOT NULL,
	PRIMARY KEY (server, date),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS logs_server_idx ON logs (SERVER);
CREATE INDEX IF NOT EXISTS logs_date_idx ON logs (date);
