DROP TABLE IF EXISTS servers;
CREATE TABLE IF NOT EXISTS servers (
	id VARCHAR(100) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	private BOOLEAN DEFAULT TRUE
);

DROP TABLE IF EXISTS logs;
CREATE TABLE IF NOT EXISTS logs (
	hash TEXT NOT NULL UNIQUE,
	server VARCHAR(100) NOT NULL REFERENCES servers (id) ON DELETE CASCADE,
	date BIGINT NOT NULL,
	guilds JSONB NOT NULL,
	players JSONB NOT NULL,
	PRIMARY KEY (server, date)
);
CREATE INDEX IF NOT EXISTS logs_server_idx ON logs (server);
CREATE INDEX IF NOT EXISTS logs_date_idx ON logs (date);
